name: Build Linux Portable Executable on Demand

on:
  workflow_dispatch:

jobs:
  build_linux:
    name: ğŸ§ Build Linux App
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: sudo apt-get update -y
      - run: sudo apt-get install -y ninja-build libgtk-3-dev
      
      - name: Build Linux App
        run: |
          flutter pub get
          flutter build linux --release

      - name: Compress Linux App
        run: |
          cd build/linux/x64/release/bundle/
          zip -r linux-x64.zip *

      - name: Upload Linux App artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64-app
          path: build/linux/x64/release/bundle/linux-x64.zip
