name: Build Windows & Linux Executable on Release

on:
  release:
    types: [published]

jobs:
  build_windows:
    name: ü™ü Build Windows App
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build windows --release
      - run: cd build/windows/x64/runner/Release/ && powershell Compress-Archive -Path * -DestinationPath windows-x64.zip
      - name: Upload Windows App to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/x64/runner/Release/windows-x64.zip

  build_linux:
    name: üêß Build Linux App
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter pub get
      - run: flutter build linux --release
      - run: cd build/linux/x64/release/bundle/ && zip -r linux-x64.zip *
      - name: Upload Linux App to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/linux/x64/release/bundle/linux-x64.zip
